use std::fs;
use std::path::Path;

const CONTENT_DIR: &str = "content";

struct Post {
    slug: String,
    title: String,
    body: String,
    date: String,
}

fn find_content() -> Vec<String> {
    walkdir::WalkDir::new(CONTENT_DIR)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().display().to_string().ends_with(".md"))
        .map(|e| e.path().display().to_string())
        .collect()
}

fn load_post(file: &str) -> Option<Post> {
    let markdown = fs::read_to_string(file).ok()?;
    let parser = pulldown_cmark::Parser::new_ext(&markdown, pulldown_cmark::Options::all());
    let mut body = String::new();
    pulldown_cmark::html::push_html(&mut body, parser);

    let slug = Path::new(file)
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("")
        .to_owned();

    let title = markdown
        .lines()
        .find(|l| l.starts_with("# "))
        .map(|l| l.trim_start_matches('#').trim().to_owned())
        .unwrap_or_else(|| slug.replace('-', " ").replace('_', " "));

    let date = markdown
        .lines()
        .find(|l| l.starts_with("date:"))
        .map(|l| l.trim_start_matches("date:").trim().to_owned())
        .unwrap_or_default();

    Some(Post { slug, title, body, date })
}

fn escape_ts_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "")
}

fn main() {
    let posts: Vec<Post> = find_content()
        .into_iter()
        .filter_map(|f| load_post(&f))
        .collect();

    let output_path = std::env::args()
        .nth(1)
        .unwrap_or_else(|| "app/blog-data.server.ts".to_owned());

    let mut posts_arr = String::from("[");
    for (i, p) in posts.iter().enumerate() {
        if i > 0 {
            posts_arr.push(',');
        }
        posts_arr.push_str(&format!(
            r#"{{"slug":"{}","title":"{}","date":"{}"}}"#,
            escape_ts_string(&p.slug),
            escape_ts_string(&p.title),
            escape_ts_string(&p.date),
        ));
    }
    posts_arr.push(']');

    let mut by_slug = String::from("{");
    for (i, p) in posts.iter().enumerate() {
        if i > 0 {
            by_slug.push(',');
        }
        by_slug.push_str(&format!(
            r#""{}": {{"slug":"{}","title":"{}","body":"{}","date":"{}"}}"#,
            escape_ts_string(&p.slug),
            escape_ts_string(&p.slug),
            escape_ts_string(&p.title),
            escape_ts_string(&p.body),
            escape_ts_string(&p.date),
        ));
    }
    by_slug.push('}');

    let output = format!(
        "// Auto-generated by src/main.rs — do not edit\nexport const posts = {};\nexport const postsBySlug: Record<string, {{ slug: string; title: string; body: string; date: string }}> = {};\n",
        posts_arr, by_slug
    );

    if let Some(parent) = Path::new(&output_path).parent() {
        let _ = fs::create_dir_all(parent);
    }
    fs::write(&output_path, output).expect("failed to write blog-data.server.ts");
    println!("wrote {}", output_path);
}
